name: demo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  carousel_slider: ^2.2.1
  font_awesome_flutter: ^8.8.1
  line_awesome_flutter: ^1.0.1
  google_fonts: ^1.1.0
  webview_flutter: ^0.3.24
  animated_text_kit: ^2.2.0
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  firebase_storage: ^4.0.0
  modal_progress_hud: ^0.1.3
  fancy_on_boarding: ^1.6.0
  shared_preferences: ^0.5.12
  flare_flutter: ^2.0.6
  url_launcher: ^5.7.5
  page_transition: ^1.1.7+2
  image_picker: ^0.6.7+11
  lottie: ^0.7.0+1
  smooth_star_rating: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  flutter_svg: 0.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/illustrations/
    - assets/icons/
    - assets/lottie/
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic